### ISSUE TITLE
Adapting the APC 40 script to work with the APC Key 25 MK2 

### ISSUE THREAD

**Issue by nzimas** [juanlittledevil/Mozaic-Scripts#1]
Considering that the APC Key 25 MK2 communication protocol is now available (https://cdn.inmusicbrands.com/akai/attachments/APC%20Key%2025%20mk2%20-%20Communication%20Protocol%20-%20v1.0.pdf), how difficult would it be to adapt your APC 40 scripts? Is it only a matter of replacing values or would it require a new logic to be written?

**Comment by juanlittledevil** [comment]
From first glance at the midi implementation, I can tell you they are quite different. The APC40 has several modes that can be defined via SysEx messages. Notice in the script I choose one that enables me to take advantage of the encoder banks a bit easier. So the first thing you'll need to do is replace that for the corresponding message intended for the APC Key.

The second big thing I noticed is that, unlike the APC40 which has each track (column) of buttons on a different MIDI channel, the APC Key seems to have all the keys mapped to channel 1. This is probably the biggest difference, and possibly the reason simply changing values won't work.

What functionality are you trying to replicate with your script? I don't own an APC key unfortunately so I can't test this for you but I'm more than happy to guide you on your journey if you provide specifics as to what you are trying to do.

**Comment by nzimas** [comment]
Thanks for the prompt feedback!

My main goal is to enable at least some visual feedback from auv3 plugins
like Loopy Pro and Koala Sampler.

But this might be a tall order, because perhaps the plugins themselves must
support this kind of feature for this particular device.

I know for a fact that these two plugins work beautifully with your
Launchpad Mini MK3, either standalone or via AUM, but the APC Key 25 MK2 is
a whole different business.

In your particular use case, what do you use the APC 40 with?

**Comment by juanlittledevil** [comment]
If what you want is visual feedback, as long as the plugins send MIDI out you can do something with that.

As to my use case; I mainly use my APC40 to control AUM so I can basically turn it into a mixer for my external gear. The majority of my audio sources come from my modular rig and I mostly use AUM so I can process the audio with effects.

* Track Faders are mapped to volume faders on AUM.
* Track arm, solo, record buttons are mapped to their corresponding tracks.
* The transports are also mapped to transport in AUM.
* The clip launch matrix I use mainly as buttons that I can map to the "show plugin" function for the plugin, this allows me to quickly press a key and bring up the plugin in question to the foreground. This is nice because with the two views that gives me a total of 80 keys, and then I have a few more with the scene launch and stop buttons, (I kept those out of the matrix on purpose because there are things I want to keep with easy access all the time and I want to eventually add more functionality to the matrix)
* The encoders are a free for all, since I have so many to choose from I tent to use it to control all sorts of plugin parameters. Some of the banks are the same on all tracks, like a channel strip on a mixer, but other banks are mapped to plugins, etc.


On a side note, looks like on the APC Keys 25 mkII midi channel determines the brightness/blink behaviour, it's so cool that you can sync the blink rate to a MIDI clock. That would certainly make some interesting visual feedback. Also, as far as I can tell it doesn't seem like have you have to put it in some kind of mode like the APC40 does. Does look like interacting over SysEx gives you a couple of extra options but nothing that warrants going that route IMO, so I'd say figure out the MIDI communication and stick with that, you'll have an easier time that way.

**Comment by juanlittledevil** [comment]
ooooh.. @nzimas looks like those knobs on the APC Key 25 send relative data. That's actually really good news for you. As you should be able to expand functionality by keeping state/values inside and using other methods like pressing a key on your keyboard or the Mosaic plugin to change the value you are accessing.

**Comment by juanlittledevil** [comment]
Haven't heard back from you in a while so I'm going to close this issue. Please feel free to reach out if you need any further assistance.

cheers,

-- Juan
